
#ifndef FINDARMORPROGRAM_SETTINGS_H
#define FINDARMORPROGRAM_SETTINGS_H
enum COLOR
{
    RED=0,
    BLUE=1,
    NORMAL=2
};
enum ID
{
    UNKNOWN=0,
    RED_HERO=1,
    RED_ENGINEER=2,
    RED_INFANTRY_3=3,
    RED_INFANTRY_4=4,
    RED_INFANTRY_5=5,
    BLUE_HERO=6,
    BLUE_ENGINEER=7,
    BLUE_INFANTRY_3=8,
    BLUE_INFANTRY_4=9,
    BLUE_INFANTRY_5=10,
};
#define ANGLE_THRESHOLD 10
#define MIN_LIGHTBAR_AREA 50
#define MAX_LIGHTBAR_AREA 32000
#endif //FINDARMORPROGRAM_SETTINGS_H
